import { brightnessCommand, powerCommand } from './candela-ble.ts';

export type Pattern = 'steady' | 'candle' | 'breathe';
export interface State {
  on: boolean;
  dim: number;
  pattern: Pattern;
}

export function isPattern(value: unknown): value is Pattern {
  return value === 'steady' || value === 'candle' || value === 'breathe';
}

// A conservative 1 Hz write rate: effects are generated by Homey, not native modes.
export function patternDim(pattern: Pattern, dim: number, elapsedMs: number, random = Math.random) {
  const factor = pattern === 'candle'
    ? 0.65 + random() * 0.35
    : 0.2 + (0.8 * (1 - Math.cos((elapsedMs / 8000) * 2 * Math.PI))) / 2;
  return Math.max(0.01, dim * factor);
}

interface Transport {
  write(packets: Buffer[], keepConnected?: boolean): Promise<void>;
  probe(): Promise<void>;
  close(): Promise<void>;
}

interface Callbacks {
  state(state: State): Promise<void>;
  available(): Promise<void>;
  unavailable(error: unknown): Promise<void>;
  setTimeout(callback: () => void, ms: number): NodeJS.Timeout;
  clearTimeout(timer: NodeJS.Timeout): void;
}

export default class CandelaController {

  private queue: Promise<void> = Promise.resolve();
  private timer?: NodeJS.Timeout;
  private stopped = false;
  private startedAt = Date.now();

  constructor(
    private readonly transport: Transport,
    private state: State,
    private readonly callbacks: Callbacks,
  ) {}

  private enqueue(operation: () => Promise<void>) {
    const result = this.queue.then(async () => {
      if (this.stopped) throw new Error('Candela device has been removed or the app has stopped');
      await operation();
    });
    this.queue = result.catch(() => {});
    return result;
  }

  private cancelTimer() {
    if (this.timer) this.callbacks.clearTimeout(this.timer);
    this.timer = undefined;
  }

  private schedule(callback: () => Promise<void>, delay: number) {
    this.cancelTimer();
    if (this.stopped) return;
    this.timer = this.callbacks.setTimeout(() => {
      this.timer = undefined;
      // Operations report failures through unavailable() before rejecting.
      callback().catch(() => {});
    }, delay);
  }

  private async failed(error: unknown) {
    this.cancelTimer();
    await this.transport.close();
    if (this.stopped) return;
    this.schedule(() => this.start(), 30000);
    await this.callbacks.unavailable(error);
  }

  start() {
    return this.enqueue(async () => {
      this.cancelTimer();
      try {
        await this.transport.probe();
        await this.callbacks.available();
        this.schedulePattern();
      } catch (error) {
        await this.failed(error);
        throw error;
      }
    });
  }

  setPower(on: boolean) {
    return this.change(() => ({ ...this.state, on }));
  }

  setDim(dim: number) {
    if (!Number.isFinite(dim) || dim < 0 || dim > 1) {
      return Promise.reject(new Error('Brightness must be between 0 and 1'));
    }
    // Zero switches off, keeping the previous positive brightness for next time.
    return this.change(() => ({ ...this.state, on: dim > 0, dim: dim || this.state.dim }));
  }

  setPattern(pattern: string) {
    if (!isPattern(pattern)) return Promise.reject(new Error('Unknown Candela pattern'));
    // Choosing an effect switches the lamp on. Steady also restores base brightness.
    return this.change(() => ({ ...this.state, pattern, on: true }));
  }

  private change(nextState: () => State) {
    return this.enqueue(async () => {
      this.cancelTimer();
      const next = nextState();
      const packets = [powerCommand(next.on)];
      if (next.on) packets.push(brightnessCommand(next.dim));
      try {
        await this.transport.write(packets, next.on && next.pattern !== 'steady');
        this.state = next;
        this.startedAt = Date.now();
        if (!this.stopped) {
          await this.callbacks.state({ ...next });
          await this.callbacks.available();
          this.schedulePattern();
        }
      } catch (error) {
        await this.failed(error);
        throw error;
      }
    });
  }

  private schedulePattern() {
    if (!this.state.on || this.state.pattern === 'steady') return;
    this.schedule(() => this.tick(), 1000);
  }

  private tick() {
    return this.enqueue(async () => {
      // A queued off/steady command may have run since this tick was scheduled.
      if (!this.state.on || this.state.pattern === 'steady') return;
      try {
        const dim = patternDim(this.state.pattern, this.state.dim, Date.now() - this.startedAt);
        await this.transport.write([brightnessCommand(dim)], true);
        this.schedulePattern();
      } catch (error) {
        await this.failed(error);
        throw error;
      }
    });
  }

  async stop() {
    this.stopped = true;
    this.cancelTimer();
    await this.queue;
    await this.transport.close();
  }

}
